version: 2
jobs:
  build:
    docker:
      - image: stmllr/docker-client

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build docker
          command: |
            sh ci_scripts/build-image.sh ci_scripts/ubuntu-16_04

      - run:
          name: Build package
          command: |
            sh ci_scripts/build-package.sh ci_scripts/ubuntu-16_04

      - run:
          name: Show build artifacts
          command: |
            ls -lR build/

workflows:
  version: 2
  ubuntu-build-pipe:
    jobs:
      - build
